# Generated by Django 4.2.3 on 2023-07-12 11:14

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('medical', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Doctor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=100, verbose_name='Имя')),
                ('last_name', models.CharField(max_length=100, verbose_name='Фамилия')),
                ('specialization', models.CharField(max_length=100, verbose_name='Должность')),
                ('contact_number', models.CharField(max_length=20, verbose_name='Телефон')),
            ],
        ),
        migrations.AlterField(
            model_name='patient',
            name='birth_date',
            field=models.DateField(verbose_name='Дата рождения'),
        ),
        migrations.AlterField(
            model_name='patient',
            name='first_name',
            field=models.CharField(max_length=50, verbose_name='Имя'),
        ),
        migrations.AlterField(
            model_name='patient',
            name='gender',
            field=models.CharField(choices=[('M', 'Мужской'), ('F', 'Женский')], max_length=10, verbose_name='Пол'),
        ),
        migrations.AlterField(
            model_name='patient',
            name='last_name',
            field=models.CharField(max_length=50, verbose_name='Фамилия'),
        ),
        migrations.AlterField(
            model_name='patient',
            name='middle_name',
            field=models.CharField(max_length=50, verbose_name='Отчество'),
        ),
        migrations.AlterField(
            model_name='patient',
            name='passport_number',
            field=models.CharField(max_length=6, verbose_name='Номер паспорта'),
        ),
        migrations.AlterField(
            model_name='patient',
            name='passport_series',
            field=models.CharField(max_length=4, verbose_name='Серия паспорта'),
        ),
    ]
