# Generated by Django 4.2.3 on 2023-07-12 11:17

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('medical', '0002_doctor_alter_patient_birth_date_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='doctor',
            name='middle_name',
            field=models.CharField(default=0, max_length=50, verbose_name='Отчество'),
            preserve_default=False,
        ),
    ]
