# Generated by Django 4.2.3 on 2023-07-17 11:02

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ('medical', '0006_alter_appointment_doctor_doctorschedule'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='patient',
            name='first_name',
        ),
        migrations.RemoveField(
            model_name='patient',
            name='last_name',
        ),
        migrations.RemoveField(
            model_name='patient',
            name='middle_name',
        ),
        migrations.RemoveField(
            model_name='patient',
            name='passport_number',
        ),
        migrations.RemoveField(
            model_name='patient',
            name='passport_series',
        ),
        migrations.AddField(
            model_name='patient',
            name='address',
            field=models.CharField(default=1, max_length=100, verbose_name='Адрес проживания'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='patient',
            name='allergies',
            field=models.TextField(default=1, verbose_name='Аллергические реакции и непереносимость лекарств'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='patient',
            name='chronic_conditions',
            field=models.TextField(default=1, verbose_name='Хронические заболевания'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='patient',
            name='contact_number',
            field=models.CharField(default=1, max_length=20, verbose_name='Контактный номер'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='patient',
            name='email',
            field=models.EmailField(default=1, max_length=100, verbose_name='Эл. почта'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='patient',
            name='full_name',
            field=models.CharField(default=1, max_length=100, verbose_name='ФИО'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='patient',
            name='insurance_number',
            field=models.CharField(default=1, max_length=20, verbose_name='Номер полиса'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='patient',
            name='medical_history',
            field=models.TextField(default=1, verbose_name='Анамнез заболеваний'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='patient',
            name='medical_tests',
            field=models.TextField(default=1, verbose_name='Результаты медицинских обследований'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='patient',
            name='military_rank',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Воинское звание'),
        ),
        migrations.AddField(
            model_name='patient',
            name='prescriptions',
            field=models.TextField(default=1, verbose_name='Рецепты и назначения лекарств'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='patient',
            name='snils_number',
            field=models.CharField(default=1, max_length=20, verbose_name='Номер СНИЛС'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='patient',
            name='surgeries',
            field=models.TextField(default=1, verbose_name='История операций и процедур'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='appointment',
            name='doctor',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='medical.doctor'),
        ),
        migrations.AlterField(
            model_name='doctorschedule',
            name='doctor',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='medical.doctor'),
        ),
        migrations.CreateModel(
            name='Visit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('visit_date', models.DateField(verbose_name='Дата посещения')),
                ('diagnosis', models.TextField(verbose_name='Диагноз')),
                ('treatment_plan', models.TextField(verbose_name='План лечения и рекомендации')),
                ('doctor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='medical.doctor')),
                ('patient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='visits',
                                              to='medical.patient')),
            ],
        ),
        migrations.CreateModel(
            name='Vaccination',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('vaccine', models.CharField(max_length=100, verbose_name='Прививка')),
                ('vaccination_date', models.DateField(verbose_name='Дата вакцинации')),
                ('patient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='vaccinations',
                                              to='medical.patient')),
            ],
        ),
    ]
