# Generated by Django 4.2.3 on 2023-07-18 11:10

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ('medical', '0007_remove_patient_first_name_remove_patient_last_name_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='AppointmentSlot',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(verbose_name='Дата приема')),
                ('start_time', models.TimeField(verbose_name='Время начала приема')),
                ('end_time', models.TimeField(verbose_name='Время окончания приема')),
            ],
        ),
        migrations.AddField(
            model_name='doctor',
            name='appointment_duration',
            field=models.PositiveIntegerField(default=15, verbose_name='Длительность приема в минутах'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='doctor',
            name='end_time',
            field=models.TimeField(default='16:30', verbose_name='Время окончания приема'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='doctor',
            name='start_time',
            field=models.TimeField(default='8:00', verbose_name='Время начала приема'),
            preserve_default=False,
        ),
        migrations.DeleteModel(
            name='Appointment',
        ),
        migrations.AddField(
            model_name='appointmentslot',
            name='doctor',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='medical.doctor'),
        ),
    ]
