# Generated by Django 4.2.3 on 2023-07-19 11:03

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ('medical', '0008_appointmentslot_doctor_appointment_duration_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Appointment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(verbose_name='Дата приема')),
                ('time', models.TimeField(verbose_name='Время приема')),
                ('appointment_duration', models.PositiveIntegerField(verbose_name='Длительность приема в минутах')),
                ('doctor_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='medical.doctor',
                                                verbose_name='ID врача')),
                ('patient_id', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE,
                                                 to='medical.patient', verbose_name='ID пациента')),
            ],
            options={
                'verbose_name': 'Запись на прием',
                'verbose_name_plural': 'Записи на прием',
            },
        ),
    ]
